# Generated by Django 5.1.1 on 2024-09-09 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('formacao_academica', models.CharField(choices=[('G', 'Graduacao'), ('M', 'Mestrado'), ('D', 'Doutorado')], default='G', max_length=30)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
