# Generated by Django 5.1.1 on 2024-09-09 04:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipe',
            name='registro_atualizado',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='equipe',
            name='registro_criado',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
