# Generated by Django 5.1.1 on 2024-09-09 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artigos', '0002_alter_artigos_options_remove_artigos_discente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artigos',
            name='ano',
            field=models.PositiveIntegerField(default=2024, verbose_name='Ano'),
        ),
    ]
